### ISSUE TITLE
[Build Issue] addons:rust does not build on aarch64

### ISSUE THREAD

**Issue by heitbaum** [LibreELEC/LibreELEC.tv#7937]
### Describe the bug
Building `addons:rust` on Ampere A1 fails.

Wrong binary snapshots (if cross required)

```
GET      rustc-snapshot (archive)
--2023-06-19 15:59:14--  https://static.rust-lang.org/dist/rustc-1.70.0-aarch64-unknown-linux-gnu.tar.xz
Resolving static.rust-lang.org (static.rust-lang.org)... 18.67.111.86, 18.67.111.17, 18.67.111.122, ...
Connecting to static.rust-lang.org (static.rust-lang.org)|18.67.111.86|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 79212028 (76M) [application/x-tar]
Saving to: '/build/sources/rustc-snapshot/rustc-snapshot-1.70.0.tar.xz'


          /build/so   0%[                    ]       0  --.-KB/s               
…
/build/sources/rust 100%[===================>]  75.54M  21.0MB/s    in 3.9s    

2023-06-19 15:59:20 (19.3 MB/s) - '/build/sources/rustc-snapshot/rustc-snapshot-1.70.0.tar.xz' saved [79212028/79212028]

    WARNING      Incorrect checksum calculated on downloaded file: got 71698cf444eef74050db821dc4df996c0f268615230099cde836e685e5b5465d wanted 7d891d3e9bc4f1151545c83cbe3bc6af9ed234388c45ca2e19641262f48615e2
```

**Comment by heitbaum** [comment]
using #7938
- ARMv7.arm - error below
- **ARMv8.aarch64 - building correctly**
- ARMv8.aarch64 - error (same as ARMv7.arm)
- Generic.x86_64- error (same as ARMv7.arm)
- Generic-legacy.x86_64- error (same as ARMv7.arm)
 
Error: `error: could not create LLVM TargetMachine for triple: aarch64-unknown-linux-gnu: No available targets are compatible with triple "aarch64-unknown-linux-gnu"`

```
Compiling rustc_smir v0.0.0 (/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/compiler/rustc_smir)
    Building [=======================> ] 297/303: rustc_query_impl, rustc_i...
     Running `/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/build/bootstrap/debug/rustc --crate-name rustc_smir --edition=2021 compiler/rustc_smir/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no -C debuginfo=0 --cfg 'feature="default"' --cfg 'feature="rustc_middle"' --cfg 'feature="rustc_span"' -Zunstable-options --check-cfg 'values(feature, "default", "rustc_middle", "rustc_span")' --check-cfg 'names()' --check-cfg 'values()' -C metadata=13e4ad6fc92547e8 -C extra-filename=-13e4ad6fc92547e8 --out-dir /build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/build/aarch64-unknown-linux-gnu/stage0-rustc/aarch64-unknown-linux-gnu/release/deps --target aarch64-unknown-linux-gnu -C linker=/build/build.LibreELEC-ARMv7.arm-12.0-devel/toolchain/bin/host-gcc -L dependency=/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/build/aarch64-unknown-linux-gnu/stage0-rustc/aarch64-unknown-linux-gnu/release/deps -L dependency=/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/build/aarch64-unknown-linux-gnu/stage0-rustc/release/deps --extern rustc_middle=/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/build/aarch64-unknown-linux-gnu/stage0-rustc/aarch64-unknown-linux-gnu/release/deps/librustc_middle-1814fd30b3242a1b.rmeta --extern rustc_span=/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/build/aarch64-unknown-linux-gnu/stage0-rustc/aarch64-unknown-linux-gnu/release/deps/librustc_span-241c702289527cd3.rmeta --extern tracing=/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/build/aarch64-unknown-linux-gnu/stage0-rustc/aarch64-unknown-linux-gnu/release/deps/libtracing-54fc414deab0faf0.rmeta --cfg=windows_raw_dylib -Csymbol-mangling-version=v0 -Zunstable-options '--check-cfg=values(bootstrap)' '--check-cfg=values(parallel_compiler)' '--check-cfg=values(no_btreemap_remove_entry)' '--check-cfg=values(crossbeam_loom)' '--check-cfg=values(span_locations)' '--check-cfg=values(rustix_use_libc)' '--check-cfg=values(emulate_second_only_system)' '--check-cfg=values(windows_raw_dylib)' -Zmacro-backtrace -Clink-args=-Wl,-z,origin '-Clink-args=-Wl,-rpath,$ORIGIN/../lib' -Csplit-debuginfo=off -Zunstable-options '-Wrustc::internal' -Cprefer-dynamic -Z binary-dep-depinfo -L native=/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/build/aarch64-unknown-linux-gnu/stage0-rustc/aarch64-unknown-linux-gnu/release/build/psm-f1ae8f7df327d47d/out`
    Building [=======================> ] 298/303: rustc_query_impl, rustc_i...
    Building [=======================> ] 299/303: rustc_query_impl, rustc_d...
    Building [=======================> ] 300/303: rustc_query_impl            
   Compiling rustc_driver v0.0.0 (/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/compiler/rustc_driver)
    Building [=======================> ] 301/303: rustc_driver                
     Running `/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/build/bootstrap/debug/rustc --crate-name rustc_driver --edition=2021 compiler/rustc_driver/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type dylib --emit=dep-info,link -C prefer-dynamic -C opt-level=3 -C embed-bitcode=no -C debuginfo=0 -Zunstable-options --check-cfg 'values(feature)' --check-cfg 'names()' --check-cfg 'values()' -C metadata=c3fa12b0462f2767 -C extra-filename=-c3fa12b0462f2767 --out-dir /build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/build/aarch64-unknown-linux-gnu/stage0-rustc/aarch64-unknown-linux-gnu/release/deps --target aarch64-unknown-linux-gnu -C linker=/build/build.LibreELEC-ARMv7.arm-12.0-devel/toolchain/bin/host-gcc -L dependency=/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/build/aarch64-unknown-linux-gnu/stage0-rustc/aarch64-unknown-linux-gnu/release/deps -L dependency=/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/build/aarch64-unknown-linux-gnu/stage0-rustc/release/deps --extern rustc_driver_impl=/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/build/aarch64-unknown-linux-gnu/stage0-rustc/aarch64-unknown-linux-gnu/release/deps/librustc_driver_impl-ff605c55eefc458a.rlib --cfg=windows_raw_dylib -Csymbol-mangling-version=v0 -Zunstable-options '--check-cfg=values(bootstrap)' '--check-cfg=values(parallel_compiler)' '--check-cfg=values(no_btreemap_remove_entry)' '--check-cfg=values(crossbeam_loom)' '--check-cfg=values(span_locations)' '--check-cfg=values(rustix_use_libc)' '--check-cfg=values(emulate_second_only_system)' '--check-cfg=values(windows_raw_dylib)' -Zmacro-backtrace -Clink-args=-Wl,-z,origin '-Clink-args=-Wl,-rpath,$ORIGIN/../lib' -Csplit-debuginfo=off -Zunstable-options '-Wrustc::internal' -Cprefer-dynamic -Z binary-dep-depinfo -L native=/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/build/aarch64-unknown-linux-gnu/stage0-rustc/aarch64-unknown-linux-gnu/release/build/psm-f1ae8f7df327d47d/out -L native=/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/build/aarch64-unknown-linux-gnu/stage0-rustc/aarch64-unknown-linux-gnu/release/build/rustc_llvm-91cbedba88345646/out -L native=/build/build.LibreELEC-ARMv7.arm-12.0-devel/toolchain/lib`
    Building [=======================> ] 302/303: rustc-main(bin)             
     Running `/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/build/bootstrap/debug/rustc --crate-name rustc_main --edition=2021 compiler/rustc/src/main.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type bin --emit=dep-info,link -C opt-level=3 -C embed-bitcode=no -C debuginfo=0 --cfg 'feature="llvm"' --cfg 'feature="max_level_info"' -Zunstable-options --check-cfg 'values(feature, "jemalloc", "jemalloc-sys", "llvm", "max_level_info", "rustc_use_parallel_compiler")' --check-cfg 'names()' --check-cfg 'values()' -C metadata=3e97df86f184d18a -C extra-filename=-3e97df86f184d18a --out-dir /build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/build/aarch64-unknown-linux-gnu/stage0-rustc/aarch64-unknown-linux-gnu/release/deps --target aarch64-unknown-linux-gnu -C linker=/build/build.LibreELEC-ARMv7.arm-12.0-devel/toolchain/bin/host-gcc -L dependency=/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/build/aarch64-unknown-linux-gnu/stage0-rustc/aarch64-unknown-linux-gnu/release/deps -L dependency=/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/build/aarch64-unknown-linux-gnu/stage0-rustc/release/deps --extern rustc_codegen_ssa=/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/build/aarch64-unknown-linux-gnu/stage0-rustc/aarch64-unknown-linux-gnu/release/deps/librustc_codegen_ssa-e9be99183a07e7bb.rlib --extern rustc_driver=/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/build/aarch64-unknown-linux-gnu/stage0-rustc/aarch64-unknown-linux-gnu/release/deps/librustc_driver-c3fa12b0462f2767.so --extern rustc_driver_impl=/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/build/aarch64-unknown-linux-gnu/stage0-rustc/aarch64-unknown-linux-gnu/release/deps/librustc_driver_impl-ff605c55eefc458a.rlib --extern rustc_smir=/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/build/aarch64-unknown-linux-gnu/stage0-rustc/aarch64-unknown-linux-gnu/release/deps/librustc_smir-13e4ad6fc92547e8.rlib --cfg=windows_raw_dylib -Csymbol-mangling-version=v0 -Zunstable-options '--check-cfg=values(bootstrap)' '--check-cfg=values(parallel_compiler)' '--check-cfg=values(no_btreemap_remove_entry)' '--check-cfg=values(crossbeam_loom)' '--check-cfg=values(span_locations)' '--check-cfg=values(rustix_use_libc)' '--check-cfg=values(emulate_second_only_system)' '--check-cfg=values(windows_raw_dylib)' -Zmacro-backtrace -Clink-args=-Wl,-z,origin '-Clink-args=-Wl,-rpath,$ORIGIN/../lib' -Csplit-debuginfo=off -Zunstable-options '-Wrustc::internal' -Cprefer-dynamic -Z binary-dep-depinfo -L native=/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/build/aarch64-unknown-linux-gnu/stage0-rustc/aarch64-unknown-linux-gnu/release/build/psm-f1ae8f7df327d47d/out -L native=/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/build/aarch64-unknown-linux-gnu/stage0-rustc/aarch64-unknown-linux-gnu/release/build/rustc_llvm-91cbedba88345646/out -L native=/build/build.LibreELEC-ARMv7.arm-12.0-devel/toolchain/lib`
    Finished release [optimized] target(s) in 11m 01s
Assembling stage1 compiler
Dirty - /build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/build/aarch64-unknown-linux-gnu/stage1-std
Building stage1 library artifacts (aarch64-unknown-linux-gnu) 
running: cd "/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0" && AR_aarch64_unknown_linux_gnu="ar" CARGO_INCREMENTAL="0" CARGO_PROFILE_RELEASE_DEBUG="0" CARGO_PROFILE_RELEASE_DEBUG_ASSERTIONS="false" CARGO_PROFILE_RELEASE_OVERFLOW_CHECKS="false" CARGO_TARGET_DIR="/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/build/aarch64-unknown-linux-gnu/stage1-std" CC_aarch64_unknown_linux_gnu="/build/build.LibreELEC-ARMv7.arm-12.0-devel/toolchain/bin/host-gcc" CFG_COMPILER_HOST_TRIPLE="aarch64-unknown-linux-gnu" CFG_DISABLE_UNSTABLE_FEATURES="1" CFG_RELEASE_CHANNEL="stable" CFLAGS_aarch64_unknown_linux_gnu="-ffunction-sections -fdata-sections -fPIC" CXXFLAGS_aarch64_unknown_linux_gnu="-ffunction-sections -fdata-sections -fPIC" CXX_aarch64_unknown_linux_gnu="/build/build.LibreELEC-ARMv7.arm-12.0-devel/toolchain/bin/host-g++" LIBC_CHECK_CFG="1" RANLIB_aarch64_unknown_linux_gnu="ar s" REAL_LIBRARY_PATH_VAR="LD_LIBRARY_PATH" RUSTBUILD_NATIVE_DIR="/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/build/aarch64-unknown-linux-gnu/native" RUSTC="/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/build/bootstrap/debug/rustc" RUSTC_BOOTSTRAP="1" RUSTC_BREAK_ON_ICE="1" RUSTC_ERROR_METADATA_DST="/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/build/tmp/extended-error-metadata" RUSTC_FORCE_UNSTABLE="1" RUSTC_INSTALL_BINDIR="bin" RUSTC_LIBDIR="/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/build/aarch64-unknown-linux-gnu/stage1/lib" RUSTC_LINT_FLAGS="-Wrust_2018_idioms -Wunused_lifetimes -Wsemicolon_in_expressions_from_macros -Dwarnings" RUSTC_REAL="/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/build/aarch64-unknown-linux-gnu/stage1/bin/rustc" RUSTC_SNAPSHOT="/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/rust-snapshot/bin/rustc" RUSTC_SNAPSHOT_LIBDIR="/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/rust-snapshot/lib" RUSTC_STAGE="1" RUSTC_SYSROOT="/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/build/aarch64-unknown-linux-gnu/stage1" RUSTC_VERBOSE="1" RUSTDOC="/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/build/bootstrap/debug/rustdoc" RUSTDOCFLAGS="-Csymbol-mangling-version=legacy -Zunstable-options -Zunstable-options --check-cfg=values(bootstrap) --check-cfg=values(stdarch_intel_sde) --check-cfg=values(no_fp_fmt_parse) --check-cfg=values(no_global_oom_handling) --check-cfg=values(no_rc) --check-cfg=values(no_sync) --check-cfg=values(freebsd12) --check-cfg=values(freebsd13) --check-cfg=values(backtrace_in_libstd) --check-cfg=values(target_env,\"libnx\") --check-cfg=values(target_arch,\"asmjs\",\"spirv\",\"nvptx\",\"xtensa\",\"loongarch64\") --check-cfg=values(target_env,\"ohos\") -Dwarnings -Wrustdoc::invalid_codeblock_attributes --crate-version 1.70.0\n(90c541806\n2023-05-31)\n(built\nfrom\na\nsource\ntarball) -Zcrate-attr=doc(html_root_url=\"[https://doc.rust-lang.org/1.70.0/\](https://doc.rust-lang.org/1.70.0//)")" RUSTDOC_REAL="/path/to/nowhere/rustdoc/not/required" RUSTFLAGS="-Csymbol-mangling-version=legacy -Zunstable-options -Zunstable-options --check-cfg=values(bootstrap) --check-cfg=values(stdarch_intel_sde) --check-cfg=values(no_fp_fmt_parse) --check-cfg=values(no_global_oom_handling) --check-cfg=values(no_rc) --check-cfg=values(no_sync) --check-cfg=values(freebsd12) --check-cfg=values(freebsd13) --check-cfg=values(backtrace_in_libstd) --check-cfg=values(target_env,\"libnx\") --check-cfg=values(target_arch,\"asmjs\",\"spirv\",\"nvptx\",\"xtensa\",\"loongarch64\") --check-cfg=values(target_env,\"ohos\") -Zmacro-backtrace -Clink-args=-Wl,-z,origin -Clink-args=-Wl,-rpath,$ORIGIN/../lib -Csplit-debuginfo=off -Cprefer-dynamic -Zinline-mir -Cembed-bitcode=yes -Zcrate-attr=doc(html_root_url=\"[https://doc.rust-lang.org/1.70.0/\](https://doc.rust-lang.org/1.70.0//)")" RUST_COMPILER_RT_ROOT="/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/src/llvm-project/compiler-rt" RUST_TEST_THREADS="4" WINAPI_NO_BUNDLED_LIBRARIES="1" __CARGO_DEFAULT_LIB_METADATA="stablestd" "/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/rust-snapshot/bin/cargo" "build" "--target" "aarch64-unknown-linux-gnu" "--release" "-Zcheck-cfg=names,values,output" "-Zbinary-dep-depinfo" "-j" "4" "-v" "--frozen" "--features" " panic-unwind backtrace profiler compiler-builtins-c" "--manifest-path" "/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/library/test/Cargo.toml" "--message-format" "json-render-diagnostics"
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/build/bootstrap/debug/rustc - --crate-name ___ --print=file-names -Csymbol-mangling-version=legacy -Zunstable-options -Zunstable-options '--check-cfg=values(bootstrap)' '--check-cfg=values(stdarch_intel_sde)' '--check-cfg=values(no_fp_fmt_parse)' '--check-cfg=values(no_global_oom_handling)' '--check-cfg=values(no_rc)' '--check-cfg=values(no_sync)' '--check-cfg=values(freebsd12)' '--check-cfg=values(freebsd13)' '--check-cfg=values(backtrace_in_libstd)' '--check-cfg=values(target_env,"libnx")' '--check-cfg=values(target_arch,"asmjs","spirv","nvptx","xtensa","loongarch64")' '--check-cfg=values(target_env,"ohos")' -Zmacro-backtrace -Clink-args=-Wl,-z,origin '-Clink-args=-Wl,-rpath,$ORIGIN/../lib' -Csplit-debuginfo=off -Cprefer-dynamic -Zinline-mir -Cembed-bitcode=yes '-Zcrate-attr=doc(html_root_url="https://doc.rust-lang.org/1.70.0/")' --target aarch64-unknown-linux-gnu --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=split-debuginfo --print=crate-name --print=cfg` (exit status: 1)
  --- stdout

  Did not run successfully: exit status: 1
  LD_LIBRARY_PATH="/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/build/aarch64-unknown-linux-gnu/stage1/lib" "/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/build/aarch64-unknown-linux-gnu/stage1/bin/rustc" "-" "--crate-name" "___" "--print=file-names" "-Csymbol-mangling-version=legacy" "-Zunstable-options" "-Zunstable-options" "--check-cfg=values(bootstrap)" "--check-cfg=values(stdarch_intel_sde)" "--check-cfg=values(no_fp_fmt_parse)" "--check-cfg=values(no_global_oom_handling)" "--check-cfg=values(no_rc)" "--check-cfg=values(no_sync)" "--check-cfg=values(freebsd12)" "--check-cfg=values(freebsd13)" "--check-cfg=values(backtrace_in_libstd)" "--check-cfg=values(target_env,\"libnx\")" "--check-cfg=values(target_arch,\"asmjs\",\"spirv\",\"nvptx\",\"xtensa\",\"loongarch64\")" "--check-cfg=values(target_env,\"ohos\")" "-Zmacro-backtrace" "-Clink-args=-Wl,-z,origin" "-Clink-args=-Wl,-rpath,$ORIGIN/../lib" "-Csplit-debuginfo=off" "-Cprefer-dynamic" "-Zinline-mir" "-Cembed-bitcode=yes" "-Zcrate-attr=doc(html_root_url=\"[https://doc.rust-lang.org/1.70.0/\](https://doc.rust-lang.org/1.70.0//)")" "--target" "aarch64-unknown-linux-gnu" "--crate-type" "bin" "--crate-type" "rlib" "--crate-type" "dylib" "--crate-type" "cdylib" "--crate-type" "staticlib" "--crate-type" "proc-macro" "--print=sysroot" "--print=split-debuginfo" "--print=crate-name" "--print=cfg" "-Wrust_2018_idioms" "-Wunused_lifetimes" "-Wsemicolon_in_expressions_from_macros" "-Dwarnings" "--sysroot" "/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/build/aarch64-unknown-linux-gnu/stage1" "-Z" "force-unstable-if-unmarked"
  -------------

  --- stderr
  error: could not create LLVM TargetMachine for triple: aarch64-unknown-linux-gnu: No available targets are compatible with triple "aarch64-unknown-linux-gnu"

command did not execute successfully: cd "/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0" && AR_aarch64_unknown_linux_gnu="ar" CARGO_INCREMENTAL="0" CARGO_PROFILE_RELEASE_DEBUG="0" CARGO_PROFILE_RELEASE_DEBUG_ASSERTIONS="false" CARGO_PROFILE_RELEASE_OVERFLOW_CHECKS="false" CARGO_TARGET_DIR="/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/build/aarch64-unknown-linux-gnu/stage1-std" CC_aarch64_unknown_linux_gnu="/build/build.LibreELEC-ARMv7.arm-12.0-devel/toolchain/bin/host-gcc" CFG_COMPILER_HOST_TRIPLE="aarch64-unknown-linux-gnu" CFG_DISABLE_UNSTABLE_FEATURES="1" CFG_RELEASE_CHANNEL="stable" CFLAGS_aarch64_unknown_linux_gnu="-ffunction-sections -fdata-sections -fPIC" CXXFLAGS_aarch64_unknown_linux_gnu="-ffunction-sections -fdata-sections -fPIC" CXX_aarch64_unknown_linux_gnu="/build/build.LibreELEC-ARMv7.arm-12.0-devel/toolchain/bin/host-g++" LIBC_CHECK_CFG="1" RANLIB_aarch64_unknown_linux_gnu="ar s" REAL_LIBRARY_PATH_VAR="LD_LIBRARY_PATH" RUSTBUILD_NATIVE_DIR="/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/build/aarch64-unknown-linux-gnu/native" RUSTC="/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/build/bootstrap/debug/rustc" RUSTC_BOOTSTRAP="1" RUSTC_BREAK_ON_ICE="1" RUSTC_ERROR_METADATA_DST="/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/build/tmp/extended-error-metadata" RUSTC_FORCE_UNSTABLE="1" RUSTC_INSTALL_BINDIR="bin" RUSTC_LIBDIR="/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/build/aarch64-unknown-linux-gnu/stage1/lib" RUSTC_LINT_FLAGS="-Wrust_2018_idioms -Wunused_lifetimes -Wsemicolon_in_expressions_from_macros -Dwarnings" RUSTC_REAL="/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/build/aarch64-unknown-linux-gnu/stage1/bin/rustc" RUSTC_SNAPSHOT="/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/rust-snapshot/bin/rustc" RUSTC_SNAPSHOT_LIBDIR="/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/rust-snapshot/lib" RUSTC_STAGE="1" RUSTC_SYSROOT="/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/build/aarch64-unknown-linux-gnu/stage1" RUSTC_VERBOSE="1" RUSTDOC="/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/build/bootstrap/debug/rustdoc" RUSTDOCFLAGS="-Csymbol-mangling-version=legacy -Zunstable-options -Zunstable-options --check-cfg=values(bootstrap) --check-cfg=values(stdarch_intel_sde) --check-cfg=values(no_fp_fmt_parse) --check-cfg=values(no_global_oom_handling) --check-cfg=values(no_rc) --check-cfg=values(no_sync) --check-cfg=values(freebsd12) --check-cfg=values(freebsd13) --check-cfg=values(backtrace_in_libstd) --check-cfg=values(target_env,\"libnx\") --check-cfg=values(target_arch,\"asmjs\",\"spirv\",\"nvptx\",\"xtensa\",\"loongarch64\") --check-cfg=values(target_env,\"ohos\") -Dwarnings -Wrustdoc::invalid_codeblock_attributes --crate-version 1.70.0\n(90c541806\n2023-05-31)\n(built\nfrom\na\nsource\ntarball) -Zcrate-attr=doc(html_root_url=\"[https://doc.rust-lang.org/1.70.0/\](https://doc.rust-lang.org/1.70.0//)")" RUSTDOC_REAL="/path/to/nowhere/rustdoc/not/required" RUSTFLAGS="-Csymbol-mangling-version=legacy -Zunstable-options -Zunstable-options --check-cfg=values(bootstrap) --check-cfg=values(stdarch_intel_sde) --check-cfg=values(no_fp_fmt_parse) --check-cfg=values(no_global_oom_handling) --check-cfg=values(no_rc) --check-cfg=values(no_sync) --check-cfg=values(freebsd12) --check-cfg=values(freebsd13) --check-cfg=values(backtrace_in_libstd) --check-cfg=values(target_env,\"libnx\") --check-cfg=values(target_arch,\"asmjs\",\"spirv\",\"nvptx\",\"xtensa\",\"loongarch64\") --check-cfg=values(target_env,\"ohos\") -Zmacro-backtrace -Clink-args=-Wl,-z,origin -Clink-args=-Wl,-rpath,$ORIGIN/../lib -Csplit-debuginfo=off -Cprefer-dynamic -Zinline-mir -Cembed-bitcode=yes -Zcrate-attr=doc(html_root_url=\"[https://doc.rust-lang.org/1.70.0/\](https://doc.rust-lang.org/1.70.0//)")" RUST_COMPILER_RT_ROOT="/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/src/llvm-project/compiler-rt" RUST_TEST_THREADS="4" WINAPI_NO_BUNDLED_LIBRARIES="1" __CARGO_DEFAULT_LIB_METADATA="stablestd" "/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/rust-snapshot/bin/cargo" "build" "--target" "aarch64-unknown-linux-gnu" "--release" "-Zcheck-cfg=names,values,output" "-Zbinary-dep-depinfo" "-j" "4" "-v" "--frozen" "--features" " panic-unwind backtrace profiler compiler-builtins-c" "--manifest-path" "/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/library/test/Cargo.toml" "--message-format" "json-render-diagnostics"
expected success, got: exit status: 101
Traceback (most recent call last):
  File "/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/src/bootstrap/bootstrap.py", line 965, in <module>
    main()
  File "/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/src/bootstrap/bootstrap.py", line 950, in main
    bootstrap(args)
  File "/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/src/bootstrap/bootstrap.py", line 925, in bootstrap
    run(args, env=env, verbose=build.verbose, is_bootstrap=True)
  File "/build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/src/bootstrap/bootstrap.py", line 167, in run
    raise RuntimeError(err)
RuntimeError: failed to run: /build/build.LibreELEC-ARMv7.arm-12.0-devel/build/rust-1.70.0/build/bootstrap/debug/bootstrap -j 4 build --stage 2 --verbose
FAILURE: scripts/build rust:host during make_host (package.mk)
*********** FAILED COMMAND ***********
python3 src/bootstrap/bootstrap.py -j ${CONCURRENCY_MAKE_LEVEL} build --stage 2 --verbose
**************************************
```
